[Icon Theme]
Name=Facia
Name[tr]=Facia
Comment=Icon theme for Pardus Xfce.
Comment[tr]=Pardus Xfce için simge teması.
Inherits=Adwaita,Tango

# List all directories
Directories=statusbar,statusbar/battery,statusbar/nm,actions,categories,places,places/16x16,places/symbolic,apps,mimes/office,mimes/audio,mimes/text,mimes/packages,mimes,devices

[statusbar]
Context=Status
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[statusbar/battery]
Context=Battery
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[statusbar/nm]
Context=Battery
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[actions]
Context=Actions
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[places]
Context=Places
Size=200
MinSize=16
MaxSize=512
Type=Scalable

[places/symbolic]
Context=Places
Size=16
MinSize=16
MaxSize=32
Type=Scalable

[places/16x16]
Context=Places
Size=16
MinSize=16
MaxSize=24
Type=Scalable

[categories]
Context=Categories
Size=64
MinSize=8
MaxSize=512
Type=Scalable

[apps]
Context=Applications
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[mimes/office]
Context=Mimetypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[mimes/audio]
Context=Mimetypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[mimes/text]
Context=Mimetypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[mimes/packages]
Context=Mimetypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[mimes]
Context=Mimetypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[devices]
Context=Mimetypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

